# Use existing image for ghdl
FROM ghdl/ghdl:ubuntu22-mcode

# Custom image metadata
LABEL maintainer="Chase Ruskin"
LABEL description="Wharf toolchain layer for ghdl"

# Enter the shell
CMD ["/bin/bash"]