name: Operating System
on:
  workflow_call:
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
    ubuntu:
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout 
          uses: actions/checkout@v4